#!/usr/bin/env python3
"""Regenerate the contributor grids in the English and Chinese READMEs."""

from __future__ import annotations

import argparse
import html
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any


API_ROOT = "https://api.github.com"
START_MARKER = "<!-- CONTRIBUTORS:START -->"
END_MARKER = "<!-- CONTRIBUTORS:END -->"
MAX_COLUMNS = 8


@dataclass
class Contributor:
    key: str
    name: str
    avatar_url: str
    profile_url: str
    contributions: int = 0


def github_get(path: str, token: str | None) -> Any:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "FinSight-AI-contributor-updater",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    request = urllib.request.Request(f"{API_ROOT}{path}", headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.load(response)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API returned HTTP {exc.code}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Unable to reach the GitHub API: {exc.reason}") from exc


def fetch_contributors(repo: str, ref: str | None, token: str | None) -> list[Contributor]:
    contributors: dict[str, Contributor] = {}
    page = 1

    while True:
        query: dict[str, str | int] = {"per_page": 100, "page": page}
        if ref:
            query["sha"] = ref
        encoded_repo = "/".join(urllib.parse.quote(part, safe="") for part in repo.split("/"))
        path = f"/repos/{encoded_repo}/commits?{urllib.parse.urlencode(query)}"
        commits = github_get(path, token)
        if not isinstance(commits, list):
            raise RuntimeError("GitHub returned an unexpected response for the commits endpoint")

        for item in commits:
            account = item.get("author")
            commit_author = item.get("commit", {}).get("author") or {}

            if account:
                login = account["login"]
                if account.get("type") == "Bot" or login.casefold().endswith("[bot]"):
                    continue
                key = f"github:{login.casefold()}"
                contributor = Contributor(
                    key=key,
                    name=login,
                    avatar_url=account["avatar_url"],
                    profile_url=account["html_url"],
                )
            else:
                name = commit_author.get("name") or "Anonymous"
                email = commit_author.get("email") or name
                if name.casefold() in {"github", "github actions"}:
                    continue
                key = f"anonymous:{email.casefold()}"
                contributor = Contributor(
                    key=key,
                    name=name,
                    avatar_url="https://github.com/ghost.png?size=96",
                    profile_url=f"https://github.com/{repo}/graphs/contributors",
                )

            existing = contributors.get(key)
            if existing:
                existing.contributions += 1
            else:
                contributor.contributions = 1
                contributors[key] = contributor

        if len(commits) < 100:
            break
        page += 1

    return sorted(
        contributors.values(),
        key=lambda contributor: (-contributor.contributions, contributor.name.casefold()),
    )


def render_grid(contributors: list[Contributor], locale: str) -> str:
    generated_note = (
        "<!-- Automatically generated by scripts/update_contributors.py. Do not edit manually. -->"
        if locale == "en"
        else "<!-- 由 scripts/update_contributors.py 自动生成，请勿手动编辑。 -->"
    )
    lines = [generated_note, "<table>", "  <tbody>"]

    for index, contributor in enumerate(contributors):
        if index % MAX_COLUMNS == 0:
            lines.append("    <tr>")

        name = html.escape(contributor.name)
        avatar_url = html.escape(contributor.avatar_url, quote=True)
        profile_url = html.escape(contributor.profile_url, quote=True)
        if locale == "zh-CN":
            contribution_text = f"{contributor.contributions} 次提交"
        else:
            noun = "commit" if contributor.contributions == 1 else "commits"
            contribution_text = f"{contributor.contributions} {noun}"

        lines.extend(
            [
                '      <td align="center" width="110">',
                f'        <a href="{profile_url}">',
                f'          <img src="{avatar_url}" width="72" height="72" alt="{name}"><br>',
                f"          <sub><b>{name}</b></sub><br>",
                f"          <sub>{contribution_text}</sub>",
                "        </a>",
                "      </td>",
            ]
        )

        if index % MAX_COLUMNS == MAX_COLUMNS - 1 or index == len(contributors) - 1:
            lines.append("    </tr>")

    lines.extend(["  </tbody>", "</table>"])
    return "\n".join(lines)


def update_readme(path: Path, rendered_grid: str, check: bool) -> bool:
    original = path.read_text(encoding="utf-8")
    start = original.find(START_MARKER)
    end = original.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise RuntimeError(f"Contributor markers are missing or invalid in {path}")

    content_start = start + len(START_MARKER)
    updated = (
        original[:content_start]
        + "\n"
        + rendered_grid
        + "\n"
        + original[end:]
    )
    if updated == original:
        return False
    if check:
        return True

    path.write_text(updated, encoding="utf-8")
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo",
        default=os.getenv("GITHUB_REPOSITORY", "juanjuandog/FinSight-AI"),
        help="GitHub repository in owner/name form",
    )
    parser.add_argument(
        "--ref",
        default=None,
        help="Branch, tag, or commit to inspect (defaults to the repository default branch)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 if either README is out of date",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.repo.count("/") != 1:
        raise RuntimeError("--repo must use the owner/name format")

    root = Path(__file__).resolve().parents[1]
    contributors = fetch_contributors(args.repo, args.ref, os.getenv("GITHUB_TOKEN"))
    if not contributors:
        raise RuntimeError("No human contributors were found")

    changed_paths = []
    for filename, locale in (("README.md", "en"), ("README.zh-CN.md", "zh-CN")):
        path = root / filename
        if update_readme(path, render_grid(contributors, locale), args.check):
            changed_paths.append(filename)

    if args.check and changed_paths:
        print(f"Out of date: {', '.join(changed_paths)}", file=sys.stderr)
        return 1
    if changed_paths:
        print(f"Updated {', '.join(changed_paths)} with {len(contributors)} contributors")
    else:
        print(f"Contributor sections are current ({len(contributors)} contributors)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
